#!/bin/env python
# -*- coding: utf8 -*-

from sys import argv
from os import environ, system, fork, execl, kill, getcwd, chdir, listdir, mkdir
from os.path import exists
from signal import SIGHUP
from time import sleep
from commands import getstatusoutput as cmd
from traceback import format_exc

initialsleep = 20

def error(expected, got):
    print "Error!  Expected:"
    print "  ", expected
    print "but got"
    print "  ", got

def listEQ(a, b, tag=None):
    print tag
    a.sort(); b.sort()
    if a==b: return
    error(b, a)

def strEQ(a, b, tag=None):
    print tag
    if a==b: return
    error(b, a)

def cleanup():
    chdir(environ['HOME'])
    if testset: system('rm -r mnt/sets/test')
    if pid!=0: system('fusermount -u ./mnt')
    kill(pid, SIGHUP)
    
testls ="""total 2
--wxr-x--T  1 rdmurray users 1 Feb 10 19:46 IMG_9137.png
-rwxr-xr-x  1 rdmurray users 1 Feb 10 19:46 IMG_9138.png
--wxr-x--T  1 rdmurray users 1 Feb 10 20:50 IMG_9139.png"""
rscls = """total 1
-rwxr-xr-x  1 rdmurray users 1 Feb  2 22:47 Now That's A Radio.jpg
-rwxr-xr-x  1 rdmurray users 1 Feb  2 22:47 Whatever You Want To Hear.jpg"""
tratls = """total 4
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 Fo da Luciano.jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 dscn5783.jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 dscn5784.jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 dscn5789.jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 il menu memorabile..jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 30 04:47 la gattona grassa da Luciano.jpg
-rwxr-xr-x  1 rdmurray users 1 Feb 17 04:57 lotti che non \xc3\xa8 lotti.jpg
-rwxr-xr-x  1 rdmurray users 1 Jan 17 07:35 ride.jpg"""

extended = False
if len(argv)>1:
    if argv[1]=='extended': extended = True
    elif argv[1].isdigit(): initialsleep = int(argv[1])

try:
    testset = False
    environ['HOME'] = getcwd()
    if not exists('mnt'): mkdir('mnt')
    pid = fork()
    if not pid: execl('../flickrfs/flickrfs.py','../flickrfs.py', './mnt')
    sleep(initialsleep)
    listEQ(listdir('mnt'), ['sets', 'tags'], 'check that base dirs exist')
    listEQ(listdir('mnt/sets'), ['flickrfstesttest'], 'check that existing test set shows up in sets')
    listEQ(listdir('mnt/sets/flickrfstesttest'), [ '.IMG_9137.meta', '.IMG_9138.meta', '.IMG_9139.meta',
        'IMG_9137.png', 'IMG_9138.png', 'IMG_9139.png'], 'check existing image set contents')
    strEQ(cmd('ls -l mnt/sets/flickrfstesttest')[1], testls, 'ls on existing set')
    mkdir('mnt/sets/test')
    testset = True
    listEQ(listdir('mnt/sets'), ['test', 'flickrfstesttest'], 'add a new test set')
    listEQ(listdir('mnt/sets/test'), [], 'check sets/test contents initially empty')
    #If we use utf8 chars in the upload, we get a UnicdeDecodeError when we try to encode to utf8.
    #system('cp screenshot_thumb.jpg mnt/sets/test:flickrfstesttest:flickrfstest/screenshot\xc3\xa8thumb.jpg')
    system('cp screenshot_thumb.jpg mnt/sets/test:flickrfstesttest:flickrfstest/screenshot_thumb.jpg')
    listEQ(listdir('mnt/sets/test'), ['screenshot_thumb.jpg'], 'look for uploaded test pic')
    listEQ(listdir('mnt/tags'), ['personal', 'public'], 'check for base tags dirs')
    listEQ(listdir('mnt/tags/public'), [], 'initially no public dirs')
    listEQ(listdir('mnt/tags/personal'), [], 'initially no personal dirs')
    mkdir('mnt/tags/personal/flickrfstesttest')
    mkdir('mnt/tags/personal/flickrfstesttest:flickrfstest')
    mkdir('mnt/stream')
    mkdir('mnt/tags/public/radio:station:college:ca')
    mkdir('mnt/tags/public/trattoriatoscana')
    sleep(15)
    #The uploaded pic does _not_ appear, and I don't know why.  I suspect it's not a flickerfs bug, but some
    # sort of delay on the flickr side, since the image does show up in our stream.
    # 20060214: the pic is appearing now, and I don't know what changed.
    listEQ(listdir('mnt/tags/personal/flickrfstesttest'), ['.IMG_9138.meta', '.IMG_9139.meta', 'IMG_9138.png',
            'IMG_9139.png', '.screenshot_thumb.meta', 'screenshot_thumb.jpg'], 'personal/flickrfstesttest should have some of our images')
    #listEQ(listdir('mnt/tags/personal/flickrfstesttest'), ['.IMG_9138.meta', '.IMG_9139.meta', 'IMG_9138.png',
    #        'IMG_9139.png'], 'personal/flickrfstesttest should have some of our images')
    listEQ(listdir('mnt/tags/personal/flickrfstesttest:flickrfstest'), ['.IMG_9139.meta', 'IMG_9139.png',
            '.screenshot_thumb.meta', 'screenshot_thumb.jpg'], 'personal/flickrfstesttest:flickrfstest should have fewer images')
    #listEQ(listdir('mnt/tags/personal/flickrfstesttest:flickrfstest'), ['.IMG_9139.meta', 'IMG_9139.png'],
    #        'personal/flickrfstesttest:flickrfstest should have fewer images')
    dirlist = listdir('mnt/stream')
    listEQ(listdir('mnt/stream'), ['.IMG_9137.meta', '.IMG_9138.meta', '.IMG_9139.meta', 'IMG_9137.png', 'IMG_9138.png', 'IMG_9139.png',
        '.screenshot_thumb.meta', 'screenshot_thumb.jpg'], 'check our image stream contents')
    listEQ(listdir('mnt/tags/public/radio:station:college:ca'), [".Now That's A Radio.meta", '.Whatever You Want To Hear.meta',
        "Now That's A Radio.jpg", 'Whatever You Want To Hear.jpg'], 'check example public tag set')
    strEQ(cmd('ls -l mnt/tags/public/radio:station:college:ca')[1], rscls, 'ls on example public tag set')
    listEQ(listdir('mnt/tags/public/trattoriatoscana'), ['Fo da Luciano.jpg', 'dscn5783.jpg',
        'dscn5784.jpg', 'dscn5789.jpg', 'il menu memorabile..jpg', 'la gattona grassa da Luciano.jpg', 'lotti che non \xc3\xa8 lotti.jpg', 'ride.jpg',
        '.Fo da Luciano.meta', '.lotti che non \xc3\xa8 lotti.meta', '.dscn5783.meta',
        '.dscn5784.meta', '.dscn5789.meta', '.il menu memorabile..meta', '.la gattona grassa da Luciano.meta', '.ride.meta'],
        'public tag set with international characters')
    strEQ(cmd('ls -l mnt/tags/public/trattoriatoscana')[1], tratls, 'ls on international char public tag set')
    if extended:
        system('fusermount -u ./mnt')
        sleep(2)
        pid2 = fork()
        if not pid2: execl('../flickrfs.py','../flickrfs.py', './mnt')
        sleep(20)
        listEQ(listdir('mnt/sets/test'), ['.screenshot_thumb.meta', 'screenshot_thumb.jpg'], 'look for uploaded test pic after restart')
        mkdir('mnt/tags/personal/flickrfstesttest')
        sleep(10)
        #See above.
        listEQ(listdir('mnt/tags/personal/flickrfstesttest'), ['.IMG_9138.meta', '.IMG_9139.meta', 'IMG_9138.png',
            'IMG_9139.png', '.screenshot_thumb.meta', 'screenshot_thumb.jpg'], 'personal/flickrfstesttest should have uploaded image')
        #listEQ(listdir('mnt/tags/personal/flickrfstesttest'), ['.IMG_9138.meta', '.IMG_9139.meta', 'IMG_9138.png',
        #    'IMG_9139.png'], 'personal/flickrfstesttest should have uploaded image (but does not)')
    else: print "NOTE: Skipped extended tests."
    

except:
    if pid==0: print format_exc()
    cleanup()
    raise

cleanup()
